# Deploy preview to Firebase Hosting when a Pull Request is opened
# Automatically creates a temporary preview URL per PR

name: Deploy Preview to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - main
      - staging

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: Web Ui
        run: npm install

      - name: Build project
        working-directory: Web Ui
        run: npm run build

      - name: Deploy to Firebase Hosting (Preview)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TDDLAB_PREVIEW_FIREBASE }}
          projectId: tddlab-preview-firebase
